// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

export const SUPABASE_URL = "https://gqgxysgqxzqgrhtlozax.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_KROts0YW3beq3hYOG3e5rg_7miIpXf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
